/* Generated By:JavaCC: Do not edit this line. LugosiConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LugosiConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int ACHAVES = 6;
  /** RegularExpression Id. */
  int FCHAVES = 7;
  /** RegularExpression Id. */
  int VAR = 8;
  /** RegularExpression Id. */
  int PONTOEVIRGULA = 9;
  /** RegularExpression Id. */
  int TIPO = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int WHILE = 12;
  /** RegularExpression Id. */
  int DO = 13;
  /** RegularExpression Id. */
  int RETURN = 14;
  /** RegularExpression Id. */
  int PRINTIO = 15;
  /** RegularExpression Id. */
  int READIO = 16;
  /** RegularExpression Id. */
  int ATRIBUICAO = 17;
  /** RegularExpression Id. */
  int APARENTESES = 18;
  /** RegularExpression Id. */
  int FPARENTESES = 19;
  /** RegularExpression Id. */
  int FUNCTION = 20;
  /** RegularExpression Id. */
  int VIRGULA = 21;
  /** RegularExpression Id. */
  int TOKEN_NUMLITERAL = 22;
  /** RegularExpression Id. */
  int TRUE = 23;
  /** RegularExpression Id. */
  int FALSE = 24;
  /** RegularExpression Id. */
  int TOKEN_ID = 25;
  /** RegularExpression Id. */
  int NUM = 26;
  /** RegularExpression Id. */
  int ID = 27;
  /** RegularExpression Id. */
  int OP = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"var\"",
    "\";\"",
    "<TIPO>",
    "\"if\"",
    "\"while\"",
    "\"do\"",
    "\"return\"",
    "\"printIO\"",
    "\"readIO\"",
    "\":=\"",
    "\"(\"",
    "\")\"",
    "\"function\"",
    "\"virgula\"",
    "<TOKEN_NUMLITERAL>",
    "\"true\"",
    "\"false\"",
    "<TOKEN_ID>",
    "<NUM>",
    "<ID>",
    "<OP>",
  };

}
